{% set name = "celeri" %}
{% set version = "0.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/celeri-{{ version }}.tar.gz
  sha256: feda82f01d95912b032901911cb44e6897e9fc416b68a35b7df7a25868afbffd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - addict
    - cartopy
    - colorcet
    - cutde >=25.7.24
    - cvxopt
    - cvxpy
    - gmsh
    - h5py
    - loguru
    - matplotlib-base
    - meshio
    - numpy
    - pandas
    - pydantic
    - pyproj
    - scipy
    - shapely
    - spherical-geometry
    - tqdm
    - xarray
    - zarr

test:
  imports:
    - celeri
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/brendanjmeade/celeri
  dev_url: https://github.com/brendanjmeade/celeri
  summary: Next generation earthquake cycle kinematics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aseyboldt
    - brendanjmeade
    - maresb
